/control/verbose 1
/geometry/source BoolInter.tg

/run/initialize


/vis/open TSG_FILE
/vis/drawVolume

/vis/viewer/set/style surface
/vis/viewer/set/hiddenEdge true
/vis/geometry/set/forceSolid all 0 true
/vis/viewer/set/background white

/vis/viewer/set/autoRefresh true
/vis/viewer/set/viewpointThetaPhi 45 45
/vis/viewer/zoom 0.5

/vis/viewer/panTo 10 10 cm

/vis/scene/add/axes 0 0 0 10 cm

/vis/viewer/refresh
/vis/viewer/flush

