/control/verbose 
/process/em/verbose 0
/process/had/verbose 0

/run/initialize

/vis/open 
/vis/drawVolume
/vis/viewer/zoom 1
/vis/scene/add/axes 0 0 0 10 cm
/vis/viewer/set/viewpointVector 1 1 1
/vis/viewer/refresh

/gps/source/add 5
/gps/particle e-
/gps/energy 2 MeV
/gps/position -10 0 0 cm
/gps/direction 1 0 0

/gps/source/add 10
/gps/particle neutron
/gps/energy 2 MeV
/gps/position 0 -10 0 cm
/gps/direction 0 1 0

/vis/scene/add/axes 0 0 0 10 cm
/vis/scene/add/gps 
/vis/scene/add/trajectories 
/vis/scene/endOfEventAction accumulate

#/vis/viewer/set/background white
#/vis/viewer/set/style s
/vis/viewer/set/viewpointVector 1 1 1
/run/beamOn 15
/vis/viewer/refresh 

